### ISSUE TITLE
in tsr-form support the new object syntax

### ISSUE THREAD

**Issue by Zachiah** [incmixlabs/incmix-tsr#81]
The Object format for `TsRuntimeObject`s was changed from something like:
```typescript
export const T_$TSR = {
    type: "object",
    properties: {
        a: { type: "string" }
    }
}
```
to something more like:
```typescript
export const T_$TSR = {
    type: "object",
    properties: {
        a: { optional: false, tsRuntimeObject: { type: "string" } }
    }
}
```

`tsr-form` needs to be updated to support that additional level of nesting

**Comment by Zachiah** [comment]
@alexisseppolabat You did this in your previous PR correct?

**Comment by alexisseppolabat** [comment]
@Zachiah Is this still relevant? Seeing as we currently have

`
export type PropertySignatureTsRuntimeObject = {
    readonly type: "propertySignature";
    readonly optional: boolean;
    readonly tsRuntimeObject: TsRuntimeObject;
} & GlobalTsRuntimeObjectKeys;
`
